services:
  - type: web
    name: linkvault-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: linkvault-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false # User must input this manually in dashboard (The Vercel URL)

databases:
  - name: linkvault-db
    databaseName: linkvault
    user: linkvault_user
    plan: free
